<?php

namespace backend\models;

//use yii\db\ActiveRecord;
use yii\base\Model;

class HourlySession extends Model
{
    public $id;
    public $user_id;
    public $start_point;
    public $finished;

    public static function tableName() {
        return "hourly_sessions";
    }


    public function fields()
    {
        return ['id', 'user_id', 'start_point', 'finished']; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['user_id', 'start_point'], 'required'],
        ];
    }

}
